apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: java
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: jibankumar/nodetest  # Your Node.js app image from the pod description
        ports:
        - containerPort: 5000       # Matches PORT=5000 from your .env
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        envFrom:                    # Links to the Secret
        - secretRef:
            name: node-app-secret
