version: '3'

services:
  app:
    build: .
    image: app6:latest
    container_name: nodeserver
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - redis
    env_file:
      - .env.production

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --requirepass redis1234 --appendonly yes

volumes:
  redis-data:
